### ISSUE TITLE
FileNotFoundError in version 0.9.44

### ISSUE THREAD

**Issue by eladnoor** [tlubitz/SBtab#59]
When installing version 0.9.44 through pip, sbtab cannot be imported anymore, and causes the following error:

```
ImportError: Failed to import test module: test_ecm
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/mnt/a0d03c98-5e23-4d9b-b2ac-6312c7f230d5/git/enzyme-cost/tests/test_ecm.py", line 13, in <module>
    from sbtab import SBtab
  File "/usr/local/lib/python3.6/dist-packages/sbtab/__init__.py", line 2, in <module>
    with open(os.path.join('sbtab', 'VERSION')) as version_file:
FileNotFoundError: [Errno 2] No such file or directory: 'sbtab/VERSION'
```

**Comment by tlubitz** [comment]
I fixed this in 0.9.45. Please close issue if it works for you.

**Comment by tlubitz** [comment]
Thanks for the tip. I'll try and do it with the pkg_resources. For now, I have revoked the version until it the issue is sorted out.

**Comment by tlubitz** [comment]
Please let me know if this works for you now on 0.9.49.

**Comment by eladnoor** [comment]
Thanks, it is working again without issues.
By the way, are you using a Continuous Integration platform for automatic testing? It should be quite easy to set up [Travis CI](ttps://travis-ci.org) for this project.
